### ISSUE TITLE
Landing page content

### ISSUE THREAD

**Issue by andrewbiang888** [chingu1991/TeamAwesomeDevelopment#1]
E-commerce Layout 

Header 
- [ ] home / menu
- [ ] 

- [ ] swipeable landing page
- [ ] interactive story slideshow
- [ ] video banner
- [ ] animated logo animation
- [ ] minimalistic
- [ ] 

- [ ] Layout
- [ ] proportions 
- [ ] animated on load
- [ ] Decide on logo animation
- [ ] on scroll

**Comment by chingu1991** [comment]
closing to move to the design
